import { type ReactNode, useEffect, useState } from "react";
import { Route, Switch, useLocation } from "wouter";
import {
  ArrowRight,
  BarChart3,
  Building2,
  CheckCircle2,
  ClipboardCheck,
  FileText,
  Home as HomeIcon,
  MapPinned,
  Menu,
  MessageSquareText,
  PhoneCall,
  SearchCheck,
  ShieldCheck,
  Star,
  TimerReset,
  Wrench,
  X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";

const projectTitle = "{{project_title}}";

const navItems = [
  { href: "/", label: "Home" },
  { href: "/services", label: "Services" },
  { href: "/contractor-marketing", label: "Contractor Marketing" },
  { href: "/process", label: "Process" },
  { href: "/proof", label: "Proof" },
  { href: "/pricing", label: "Pricing" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];

const whatWeBuild = [
  { icon: <HomeIcon className="h-6 w-6" />, title: "Contractor Website Buildout", body: "Service pages, location pages, proof sections, trust signals, project structure, and quote buttons that make it easy for a homeowner to take the next step.", bullets: ["Service and city pages", "Clear quote requests", "Project proof structure"] },
  { icon: <PhoneCall className="h-6 w-6" />, title: "Lead Capture and Routing", body: "Quote forms, call prompts, estimate requests, source notes, and inbox or CRM handoff so new opportunities do not sit unseen.", bullets: ["Call and form capture", "Trade-specific requests", "Lead source notes"] },
  { icon: <MessageSquareText className="h-6 w-6" />, title: "Follow-Up Automation", body: "Missed-call text-back, form response, appointment reminders, old-lead follow-up, and review requests planned around the way contractors actually sell.", bullets: ["Faster first response", "Missed-call recovery", "Old lead follow-up"] },
  { icon: <MapPinned className="h-6 w-6" />, title: "Local Search and Campaign Pages", body: "Roofing, remodeling, exterior, concrete, fencing, HVAC, plumbing, electrical, and service-area pages built around real local searches.", bullets: ["Trade-specific pages", "Service-area depth", "Campaign landing pages"] },
  { icon: <BarChart3 className="h-6 w-6" />, title: "Reporting and Improvement", body: "Track calls, forms, campaign sources, booked estimates, lead quality, and the next monthly fixes that should move the business forward.", bullets: ["Call and form tracking", "Booked estimate review", "Monthly priorities"] },
];

const tradeNotes = [
  { trade: "Roofing", copy: "Storms create demand fast. Roof repair, replacement, inspection, and insurance-claim pages need to make the next call easy." },
  { trade: "Remodeling", copy: "Homeowners need trust before they invite a crew into their home. The site should explain the planning process and show real project proof." },
  { trade: "Exterior and specialty trades", copy: "Fencing, concrete, siding, gutters, HVAC, plumbing, electrical, and similar trades need service-specific pages and fast response." },
  { trade: "Local service operators", copy: "Local businesses still need clear offers, proof, simple request forms, and follow-up that does not let good opportunities go cold." },
];

const fixFirst = ["Weak homepage message", "Missing service pages", "No local or service-area depth", "Contact forms with no follow-up", "Missed calls", "No review or proof capture process", "No tracking on calls and forms", "Ads pointing to generic pages", "Old leads never followed up"];
const processSteps = [["01", "Audit the leaks", "Trace calls, forms, ads, service pages, local pages, and follow-up to find where qualified leads are getting lost."], ["02", "Rebuild the message and pages", "Sharpen the homepage, service pages, service-area pages, proof sections, and quote prompts so buyers understand why they should call."], ["03", "Wire requests and follow-up", "Plan form fields, call prompts, reminders, missed-call recovery, and old-lead follow-up around how the business sells."], ["04", "Launch local or campaign pages", "Build pages around the actual work: repair, replacement, installation, inspection, maintenance, emergency jobs, and service areas."], ["05", "Track calls, forms, and booked work", "Separate traffic from leads, leads from booked estimates, and booked estimates from good-fit jobs."], ["06", "Improve monthly", "Review lead quality, page gaps, follow-up speed, proof needs, and campaign waste. Then fix the next highest-impact issue."]];
const proofItems = ["Before/after project photos", "Customer review capture", "Service-specific trust proof", "Call and form tracking", "Booked estimate reporting", "Campaign source review"];
const pricing = [
  { name: "Website Cleanup", fit: "For contractors who already have a site, but it does not explain the work clearly or bring in enough estimate requests.", includes: ["Clear homepage message", "Main service pages", "Better request-a-quote page", "Photos, reviews, and trust sections", "Basic call and form tracking"] },
  { name: "Lead System Buildout", fit: "For contractors who need the website, quote forms, missed-call follow-up, reviews, and local pages working together.", includes: ["New site or full rebuild", "Quote forms by service", "Missed-call and form follow-up plan", "City and service pages", "Simple lead report"] },
  { name: "Monthly Growth Help", fit: "For contractors who are getting calls or clicks, but want better jobs, faster follow-up, and less wasted marketing money.", includes: ["Monthly lead review", "Fix weak pages", "Add new service or city pages", "Improve reviews and job photos", "Bring old leads back"] },
];
const pricingClients = ["Roofers who need storm, repair, replacement, and inspection leads", "Remodelers who need homeowners to trust them before the first call", "Concrete, fencing, siding, gutter, and exterior crews that need local jobs", "HVAC, plumbing, electrical, and service trades that need fast response", "Local service businesses that need more calls, better forms, and clearer follow-up"];

function AppLink({ href, className, children, onClick, ariaLabel }: { href: string; className?: string; children: ReactNode; onClick?: () => void; ariaLabel?: string }) {
  const [, setLocation] = useLocation();
  return (
    <a href={href} className={className} aria-label={ariaLabel} onClick={(event) => {
      if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.altKey || event.ctrlKey || event.shiftKey) return;
      event.preventDefault();
      onClick?.();
      setLocation(href);
      window.scrollTo(0, 0);
    }}>{children}</a>
  );
}

function Shell({ children }: { children: ReactNode }) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const closeMenu = () => setMobileMenuOpen(false);
  return (
    <div className="min-h-screen bg-zinc-950 text-white font-sans selection:bg-blue-500/30">
      <header className="fixed top-0 z-50 w-full border-b border-white/10 bg-zinc-950/92 backdrop-blur-xl">
        <div className="container mx-auto flex h-20 items-center justify-between px-5 sm:px-6">
          <AppLink href="/" className="flex items-center gap-3" onClick={closeMenu} ariaLabel={`${projectTitle} home`}><div className="flex h-11 w-11 items-center justify-center rounded-md bg-blue-600 font-black tracking-tight shadow-lg shadow-blue-600/20">{projectTitle.slice(0, 2).toUpperCase()}</div><span className="text-base font-black tracking-tight sm:text-xl">{projectTitle}</span></AppLink>
          <nav className="hidden items-center gap-5 text-sm font-semibold text-zinc-300 xl:flex">{navItems.map((item) => <AppLink key={item.href} href={item.href} className="transition-colors hover:text-white">{item.label}</AppLink>)}</nav>
          <AppLink href="/contact" className="hidden md:block"><Button className="bg-blue-600 font-bold hover:bg-blue-700">Request a Growth Audit</Button></AppLink>
          <button className="rounded-lg p-3 text-zinc-200 xl:hidden" onClick={() => setMobileMenuOpen((open) => !open)} aria-label={mobileMenuOpen ? "Close menu" : "Open menu"}>{mobileMenuOpen ? <X /> : <Menu />}</button>
        </div>
        {mobileMenuOpen && <div className="border-t border-white/10 bg-zinc-950 px-6 py-6 xl:hidden"><nav className="grid gap-3">{navItems.map((item) => <AppLink key={item.href} href={item.href} onClick={closeMenu} className="rounded-xl border border-white/10 px-4 py-3 text-zinc-200">{item.label}</AppLink>)}</nav></div>}
      </header>
      <main className="pt-20">{children}</main><StickyAuditRail />
      <footer className="border-t border-white/10 bg-black px-6 py-12"><div className="container mx-auto grid gap-8 text-sm text-zinc-400 md:grid-cols-[1.2fr_0.8fr_0.8fr]"><div><div className="font-bold uppercase tracking-wide text-zinc-200">{projectTitle}</div><p className="mt-4 max-w-xl leading-7">Launch-ready contractor growth site with request capture, follow-up planning, trust proof, and booked estimate paths.</p></div><div><p className="font-bold text-white">Explore</p><div className="mt-4 grid gap-2">{navItems.slice(0, 6).map((item) => <AppLink key={item.href} href={item.href} className="hover:text-white">{item.label}</AppLink>)}</div></div><div><p className="font-bold text-white">Contact</p><div className="mt-4 grid gap-2"><AppLink href="/contact" className="hover:text-white">Request a Project Review</AppLink><span>Veteran-owned ready / Remote capable</span></div></div></div></footer>
    </div>
  );
}

function HeroBand({ eyebrow, title, body, primary = "Request a Project Review", secondary = "See What We Fix", cta = true }: { eyebrow: string; title: string; body: string; primary?: string; secondary?: string; cta?: boolean }) {
  return <section className="relative overflow-hidden px-6 py-20 sm:py-28"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top_left,rgba(37,99,235,0.32),transparent_34%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,0.18),transparent_28%),linear-gradient(135deg,rgba(12,18,36,1),rgba(9,9,11,1))]" /><div className="absolute inset-0 -z-10 opacity-30 digital-grid" /><div className="container mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_0.9fr] lg:items-center"><div className="fadeIn"><Badge className="mb-6 border-blue-500/30 bg-blue-500/10 px-4 py-1.5 text-sm font-semibold text-blue-300 shadow-lg shadow-blue-500/10">{eyebrow}</Badge><h1 className="max-w-5xl text-5xl font-black leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl"><span className="text-glow-blue">{title}</span></h1><p className="mt-7 max-w-3xl text-lg leading-8 text-zinc-300 sm:text-xl">{body}</p>{cta && <div className="mt-10 flex flex-col gap-4 sm:flex-row"><AppLink href="/contact"><Button size="lg" className="h-14 bg-blue-600 px-8 font-bold shadow-2xl shadow-blue-600/25 hover:bg-blue-700">{primary} <ArrowRight className="ml-2 h-5 w-5" /></Button></AppLink><AppLink href="/services"><Button variant="outline" size="lg" className="h-14 border-white/15 bg-white/5 px-8 font-bold text-white hover:bg-white/10">{secondary}</Button></AppLink></div>}</div><LeadOpsVisual /></div></section>;
}

function LeadOpsVisual() {
  const metricSets = [[["Calls", "38"], ["Speed", "2m"], ["Booked", "21"]], [["Sources", "7"], ["Leaks", "4"], ["Follow-up", "12"]], [["Pages", "24"], ["Proof", "18"], ["Waste", "31%"]]];
  const [metricIndex, setMetricIndex] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setMetricIndex((index) => (index + 1) % metricSets.length), 2400); return () => window.clearInterval(timer); }, [metricSets.length]);
  return <div className="relative rounded-[2rem] border border-blue-400/20 bg-white/[0.06] p-5 shadow-2xl shadow-blue-950/40 backdrop-blur"><div className="mb-5 flex items-center justify-between"><span className="font-bold text-blue-100">Project Readiness Visual</span><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-200">LIVE REVIEW</span></div><div className="grid gap-4">{metricSets[metricIndex].map(([label, value]) => <div key={label} className="rounded-2xl border border-white/10 bg-black/30 p-4"><div className="flex items-center justify-between"><span className="text-sm text-zinc-400">{label}</span><span className="text-3xl font-black text-white">{value}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-blue-500 pulseBar" /></div></div>)}</div><div className="mt-5 rounded-2xl border border-blue-300/20 bg-blue-500/10 p-4 text-sm leading-6 text-blue-100">Website → quote request → fast follow-up → booked estimate. Make the next step obvious before the first call.</div></div>;
}

function StickyAuditRail() { return <AppLink href="/contact" className="fixed bottom-6 right-6 z-40 hidden rounded-full border border-blue-400/25 bg-blue-600/90 px-5 py-3 text-sm font-black text-white shadow-2xl shadow-blue-900/40 backdrop-blur transition hover:-translate-y-1 hover:bg-blue-500 lg:inline-flex">Find your lead leak <ArrowRight className="ml-2 h-4 w-4" /></AppLink>; }
function SectionIntro({ badge, title, body }: { badge: string; title: string; body: string }) { return <div className="mb-14 max-w-3xl"><Badge className="mb-4 border-white/10 bg-white/5 text-zinc-300">{badge}</Badge><h2 className="text-4xl font-black tracking-tight sm:text-5xl">{title}</h2><p className="mt-5 text-lg leading-8 text-zinc-400">{body}</p></div>; }

function LeadFlowLineSection() { return <section className="px-6 py-24"><div className="container mx-auto"><SectionIntro badge="Project request path" title="One clean line from click to booked estimate." body="The site should make the next step obvious. Visitors see the work, the trust proof, and the request path. The business gets a repeatable way to handle calls, forms, follow-up, proof, and reporting." /><div className="grid gap-4 md:grid-cols-5">{["Website", "Capture", "Follow-up", "Booked", "Improve"].map((step, index) => <div key={step} className="relative rounded-2xl border border-white/10 bg-zinc-900/80 p-5"><div className="text-sm font-black text-blue-300">0{index + 1}</div><h3 className="mt-2 text-xl font-black">{step}</h3>{index < 4 && <div className="absolute -right-3 top-1/2 hidden h-0.5 w-6 bg-blue-400 md:block" />}</div>)}</div></div></section>; }
function BuildSection() { return <section className="px-6 py-24"><div className="container mx-auto"><SectionIntro badge="What gets built" title="The website is only one part. The whole lead path has to work." body="A sharp page helps, but contractors also need requests, proof, follow-up, and tracking built around the site." /><div className="grid gap-6 lg:grid-cols-3">{whatWeBuild.map((item) => <Card key={item.title} className="border-white/10 bg-zinc-900/80 text-white transition hover:-translate-y-1 hover:border-blue-400/30"><CardHeader><div className="mb-3 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-blue-500/15 text-blue-300">{item.icon}</div><CardTitle>{item.title}</CardTitle><CardDescription className="text-zinc-400">{item.body}</CardDescription></CardHeader><CardContent><ul className="space-y-2">{item.bullets.map((bullet) => <li key={bullet} className="flex gap-2 text-sm text-zinc-300"><CheckCircle2 className="h-4 w-4 text-blue-400" />{bullet}</li>)}</ul></CardContent></Card>)}</div></div></section>; }
function LeadLeakAudit() { const [active, setActive] = useState("We miss calls or call back too late"); return <section className="px-6 py-24"><div className="container mx-auto rounded-[2rem] border border-blue-400/20 bg-blue-500/10 p-8"><SectionIntro badge="Lead leak audit" title="Let prospects find their leak before they call." body="Useful interaction beats brochure copy. This checklist helps a buyer recognize the first weak spot." /><div className="grid gap-3 md:grid-cols-2">{["We miss calls or call back too late", "Forms do not trigger fast follow-up", "Our pages do not show enough trust proof", "We lack service-area/local pages", "We do not know which leads become jobs"].map((item) => <button key={item} onClick={() => setActive(item)} className={`rounded-2xl border p-4 text-left font-bold ${active === item ? "border-blue-300 bg-blue-500/20 text-white" : "border-white/10 bg-black/20 text-zinc-300"}`}>{item}</button>)}</div><h3 className="mt-8 text-2xl font-black text-blue-100">Likely first fix: {active.includes("calls") ? "missed-call response" : active.includes("Forms") ? "form follow-up plan" : active.includes("proof") ? "proof section rebuild" : active.includes("area") ? "local page buildout" : "call/form tracking"}</h3></div></section>; }
function BeforeAfterComparison() { const bad = ["Generic homepage", "One contact form", "No service-area depth", "Old proof", "No clear lead source"]; const good = ["Service-specific message", "Quote flow and call prompts", "Local pages", "Reviews and job photos", "Know where good jobs came from"]; return <section className="px-6 py-24"><div className="container mx-auto"><SectionIntro badge="Before / after" title="Show the difference between a website and a lead system." body="The page should make the transformation easy to understand." /><div className="grid gap-6 lg:grid-cols-2"><ComparisonPanel title="Typical contractor site" items={bad} tone="muted" /><ComparisonPanel title="Premium lead system" items={good} tone="blue" /></div></div></section>; }
function ComparisonPanel({ title, items, tone }: { title: string; items: string[]; tone: "muted" | "blue" }) { const isBlue = tone === "blue"; return <div className={`rounded-[2rem] border p-6 ${isBlue ? "border-blue-400/30 bg-blue-500/10" : "border-white/10 bg-zinc-900/70"}`}><h3 className="text-3xl font-black text-white">{title}</h3><div className="mt-6 grid gap-3">{items.map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-black/20 p-4">{isBlue ? <CheckCircle2 className="h-5 w-5 shrink-0 text-blue-300" /> : <X className="h-5 w-5 shrink-0 text-zinc-500" />}<span className="font-semibold text-zinc-200">{item}</span></div>)}</div></div>; }
function ContractorMarketing() { return <section className="px-6 py-24"><div className="container mx-auto grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><SectionIntro badge="Contractor marketing" title="Different trades lose leads in different places." body="Roofing, remodeling, exterior work, mechanical trades, and specialty services each need different pages, proof, and response speed." /><div className="grid gap-5">{tradeNotes.map((item) => <Card key={item.trade} className="border-white/10 bg-zinc-900/80 text-white"><CardHeader><CardTitle className="flex items-center gap-3 text-2xl"><Building2 className="h-6 w-6 text-blue-300" />{item.trade}</CardTitle><CardDescription className="text-base leading-7 text-zinc-400">{item.copy}</CardDescription></CardHeader></Card>)}</div></div></section>; }
function FixFirstSection() { return <section className="bg-blue-600/5 px-6 py-24"><div className="container mx-auto"><SectionIntro badge="What we fix first" title="Fix the leaks that cost jobs before adding more traffic." body="More clicks do not help if calls are missed, pages are weak, forms are ignored, and nobody knows which leads turned into booked estimates." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{fixFirst.map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-zinc-900/80 p-5"><Wrench className="h-5 w-5 shrink-0 text-blue-400" /><span className="font-semibold text-zinc-200">{item}</span></div>)}</div></div></section>; }
function ProcessSection() { return <section className="px-6 py-24"><div className="container mx-auto"><SectionIntro badge="Build process" title="A clear path from leak audit to monthly improvement." body="The work starts by finding the weak spots. Then rebuild the message, wire follow-up, launch pages, and improve based on lead quality." /><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{processSteps.map(([num, title, body]) => <Card key={num} className="border-white/10 bg-zinc-900/80 text-white"><CardHeader><div className="text-5xl font-black text-blue-400">{num}</div><CardTitle className="text-2xl">{title}</CardTitle><CardDescription className="text-base leading-7 text-zinc-400">{body}</CardDescription></CardHeader></Card>)}</div></div></section>; }
function ProofSection() { return <section className="bg-white/[0.02] px-6 py-24"><div className="container mx-auto"><SectionIntro badge="Proof" title="Proof is built into the system." body="The site should collect and publish proof contractors already earn on jobs." /><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{proofItems.map((item) => <Card key={item} className="border-white/10 bg-zinc-900/80 text-white"><CardHeader><Star className="h-6 w-6 text-blue-300" /><CardTitle>{item}</CardTitle><CardDescription className="text-zinc-400">Plain-English proof that makes buyers more comfortable before they call.</CardDescription></CardHeader></Card>)}</div></div></section>; }
function Services() { return <><HeroBand eyebrow="Services" title="Lead capture, follow-up, trust, and tracking built around your website." body="Build the practical pieces contractors need to turn visitors into calls, forms, booked estimates, and better-fit jobs." /><BuildSection /><FixFirstSection /><CTA /></>; }
function ContractorPage() { return <><HeroBand eyebrow="Contractor Marketing" title="Plain-spoken marketing for contractors who need booked work, not agency theater." body="Roofing, remodeling, fencing, concrete, HVAC, plumbing, electrical, exterior services, and local trades need pages and follow-up that match how people buy urgent and high-trust work." /><ContractorMarketing /><ProcessSection /><CTA /></>; }
function Process() { return <><HeroBand eyebrow="Process" title="Find the leaks. Rebuild the path. Track the jobs." body="A practical path for operators who need fixes, not a deck full of marketing talk." /><ProcessSection /><CTA /></>; }
function Proof() { return <><HeroBand eyebrow="Proof" title="Collect the proof your next customer needs before they call." body="Before-and-after photos, reviews, service proof, call tracking, form tracking, and booked estimate reporting make the business easier to trust." /><ProofSection /><CTA /></>; }
function About() { return <><HeroBand eyebrow="About" title="Veteran-owned contractor marketing built for operators, not agency theater." body={`${projectTitle} is positioned around disciplined execution: clear pages, fast lead response, visible proof, and a practical growth path for Southeast Kansas roofing, remodeling, and local-service crews.`} /><section className="px-6 py-24"><div className="container mx-auto grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><Badge className="mb-4 border-blue-400/20 bg-blue-500/10 text-blue-200">Service standard</Badge><h2 className="text-4xl font-black tracking-tight sm:text-5xl">Serious trades need a serious lead system.</h2><p className="mt-5 text-lg leading-8 text-zinc-400">This page is not filler. It explains who the company serves, why the site exists, and how the marketing system supports trust before the first call.</p></div><div className="grid gap-4 sm:grid-cols-2">{["Veteran-owned credibility", "Roofing and remodeling focus", "Service-area page strategy", "Quote path clarity", "Proof and review capture", "Follow-up discipline"].map((item) => <div key={item} className="rounded-2xl border border-white/10 bg-zinc-900/80 p-5"><CheckCircle2 className="mb-3 h-6 w-6 text-blue-300" /><h3 className="font-black text-white">{item}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">Built into the site so buyers understand the company faster and know what to do next.</p></div>)}</div></div></section><ProofSection /><CTA /></>; }
function Pricing() { return <><HeroBand eyebrow="Pricing" title="Pick the lane that matches where the business is right now." body="No mystery packages. Look at the site, trade, service area, and where leads are getting lost, then scope the work that needs done." /><section className="px-6 pb-24"><div className="container mx-auto"><div className="mb-10 rounded-[2rem] border border-blue-400/20 bg-blue-500/10 p-6 sm:p-8"><h2 className="text-3xl font-black">Who this is built for</h2><p className="mt-3 max-w-3xl leading-7 text-zinc-300">This is for working contractors and local service crews that need more good calls, cleaner quote requests, faster follow-up, and a website that helps sell the job before the first conversation.</p><div className="mt-6 grid gap-3 md:grid-cols-2">{pricingClients.map((client) => <div key={client} className="flex gap-3 rounded-2xl border border-white/10 bg-black/20 p-4 text-zinc-200"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-blue-300" /><span className="font-semibold">{client}</span></div>)}</div></div><div className="grid gap-6 lg:grid-cols-3">{pricing.map((plan) => <Card key={plan.name} className="border-white/10 bg-zinc-900/80 text-white"><CardHeader><CardTitle className="text-2xl">{plan.name}</CardTitle><p className="text-lg font-bold text-blue-300">Priced after we see the job</p><CardDescription className="text-base leading-7 text-zinc-400">{plan.fit}</CardDescription></CardHeader><CardContent><ul className="space-y-3">{plan.includes.map((feature) => <li key={feature} className="flex gap-2 text-zinc-300"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-blue-400" />{feature}</li>)}</ul><AppLink href="/contact" className="mt-8 block"><Button className="w-full bg-blue-600 hover:bg-blue-700">Talk through my situation</Button></AppLink></CardContent></Card>)}</div></div></section></>; }
function Contact() { const [submitted, setSubmitted] = useState(false); return <><HeroBand eyebrow="Contact" title="Find where your leads are leaking." body="If the website gets traffic but does not reliably turn visitors into calls, forms, booked estimates, and follow-up, map the weak spots and show what to fix first." cta={false} /><section className="px-6 pb-24"><div className="container mx-auto grid gap-10 lg:grid-cols-[0.85fr_1.15fr]"><div className="rounded-[2rem] border border-white/10 bg-zinc-900/80 p-8"><h2 className="text-3xl font-black">What the Growth Audit looks at</h2><div className="mt-6 grid gap-4">{[[<ClipboardCheck className="h-5 w-5" />, "Homepage message and quote step"], [<FileText className="h-5 w-5" />, "Service pages and service-area depth"], [<PhoneCall className="h-5 w-5" />, "Calls, forms, routing, and follow-up"], [<ShieldCheck className="h-5 w-5" />, "Reviews, proof, photos, and trust gaps"], [<SearchCheck className="h-5 w-5" />, "Campaign traffic and local search gaps"], [<TimerReset className="h-5 w-5" />, "Old leads that can be followed up"]].map(([icon, text]) => <div key={String(text)} className="flex gap-3 text-zinc-300"><span className="text-blue-300">{icon}</span>{text}</div>)}</div></div><form className="rounded-[2rem] border border-white/10 bg-zinc-900 p-6 sm:p-8" onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}>{submitted ? <div className="rounded-2xl border border-emerald-400/30 bg-emerald-500/10 p-6" role="status"><CheckCircle2 className="mb-4 h-10 w-10 text-emerald-300" /><h3 className="text-2xl font-bold">Growth audit request drafted.</h3><p className="mt-3 leading-7 text-zinc-300">Connect an inbox or CRM endpoint before using the form for live lead collection.</p><Button type="button" className="mt-6 bg-blue-600 hover:bg-blue-700" onClick={() => setSubmitted(false)}>Send another request</Button></div> : <div className="grid gap-5"><Field label="Name"><Input required name="name" className="h-12 border-white/10 bg-black/30" /></Field><Field label="Company"><Input required name="company" className="h-12 border-white/10 bg-black/30" /></Field><Field label="Trade/service"><Input required name="trade" placeholder="Roofing, remodeling, HVAC, plumbing..." className="h-12 border-white/10 bg-black/30" /></Field><Field label="Biggest lead problem"><Input required name="problem" placeholder="Missed calls, weak pages, slow follow-up..." className="h-12 border-white/10 bg-black/30" /></Field><Button type="submit" size="lg" className="h-14 bg-blue-600 font-black hover:bg-blue-700">REQUEST A GROWTH AUDIT</Button></div>}</form></div></section></>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="grid gap-2"><Label className="font-bold text-zinc-200">{label}</Label>{children}</div>; }
function CTA() { return <section className="px-6 py-24"><div className="container mx-auto rounded-[2rem] border border-blue-500/20 bg-blue-600/10 p-8 sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><Badge className="mb-4 bg-blue-500/20 text-blue-200">Next step</Badge><h2 className="text-4xl font-black tracking-tight">Find where your leads are leaking.</h2><p className="mt-4 max-w-3xl leading-8 text-zinc-300">If calls, forms, traffic, proof, and follow-up are not turning into booked estimates, map the weak spots and show what to fix first.</p></div><AppLink href="/contact"><Button size="lg" className="h-14 bg-blue-600 px-8 font-bold hover:bg-blue-700">Request a Growth Audit <ArrowRight className="ml-2 h-5 w-5" /></Button></AppLink></div></div></section>; }
function Home() { return <><HeroBand eyebrow="Premium contractor marketing starter" title="Stop losing good leads after they hit your website." body={`${projectTitle} is structured as a serious contractor marketing site with quote paths, proof, follow-up, and local pages baked in from the start.`} /><LeadFlowLineSection /><BuildSection /><LeadLeakAudit /><BeforeAfterComparison /><ContractorMarketing /><FixFirstSection /><ProcessSection /><ProofSection /><CTA /></>; }
function NotFound() { return <HeroBand eyebrow="404" title="Page not found." body="That route is not available. Use the navigation to get back to the site." />; }

export default function App() {
  return <Shell><Switch><Route path="/" component={Home} /><Route path="/services" component={Services} /><Route path="/contractor-marketing" component={ContractorPage} /><Route path="/industries" component={ContractorPage} /><Route path="/case-studies" component={Proof} /><Route path="/process" component={Process} /><Route path="/proof" component={Proof} /><Route path="/pricing" component={Pricing} /><Route path="/about" component={About} /><Route path="/resources" component={Process} /><Route path="/service-area" component={ContractorPage} /><Route path="/service-areas" component={ContractorPage} /><Route path="/gallery" component={Proof} /><Route path="/contact" component={Contact} /><Route component={NotFound} /></Switch></Shell>;
}
